const menu = [
  {
    id: 1,
    title: 'Pancakes',
    category: 'Breakfast',
    price: 5,
    img: './images/pancakes.jpg',
    desc: `Delicious pancakes to fill your stomach`,
  },
  {
    id: 2,
    title: 'Cereal',
    category: 'Breakfast',
    price: 3,
    img: './images/cereal.jpg',
    desc: `Healthy cereal to start your day`,
  },
  {
    id: 3,
    title: 'Croissants',
    category: 'Breakfast',
    price: 4,
    img: './images/croissants.jpg',
    desc: `Freshly baked croissants`,
  },
  {
    id: 4,
    title: 'Cheeseburger',
    category: 'Main',
    price: 8,
    img: './images/cheeseburger.jpg',
    desc: `Angus beef cheeseburger`,
  },
  {
    id: 5,
    title: 'Panini',
    category: 'Main',
    price: 7,
    img: './images/panini.jpg',
    desc: `Tasty cheese and tomato panini`,
  },
  {
    id: 6,
    title: 'Salad',
    category: 'Main',
    price: 7,
    img: './images/salad.jpg',
    desc: `A healthy and hearty salad`,
  },
  {
    id: 7,
    title: 'Waffles',
    category: 'Dessert',
    price: 5,
    img: './images/waffles.jpg',
    desc: `Delicious Belgian waffles`,
  },
  {
    id: 8,
    title: 'Mille Feuille',
    category: 'Dessert',
    price: 6,
    img: './images/millefeuille.jpg',
    desc: `Succulent mille feuille`,
  },
  {
    id: 9,
    title: 'Ice Cream',
    category: 'Dessert',
    price: 4,
    img: './images/icecream.jpg',
    desc: `Classic ice cream`,
  },
  {
    id: 10,
    title: 'Milkshake',
    category: 'Dessert',
    price: 4,
    img: './images/milkshake.jpg',
    desc: `Delicious milkshake in various flavours`,
  },
  {
    id: 11,
    title: 'Orange Juice',
    category: 'Drinks',
    price: 2,
    img: './images/orangejuice.jpg',
    desc: `Freshly squeezed orange juice`,
  },
  {
    id: 12,
    title: 'Soda',
    category: 'Drinks',
    price: '1.50',
    img: './images/coke.jpg',
    desc: `A selection of popular sodas`,
  },
  {
    id: 13,
    title: 'Tea',
    category: 'Drinks',
    price: 2,
    img: './images/tea.jpg',
    desc: `English breakfast tea`,
  },
  {
    id: 14,
    title: 'Coffee',
    category: 'Drinks',
    price: 2,
    img: './images/coffee.jpg',
    desc: `Fresh coffee`,
  },
]

export default menu;