const menu = [
  {
    id: 1,
    title: 'pancakes',
    category: 'breakfast',
    price: 5,
    img: './images/pancakes',
    desc: `Delicious pancakes to fill your stomach`,
  },
  {
    id: 2,
    title: 'cereal',
    category: 'breakfast',
    price: 3,
    img: './images/cereal',
    desc: `Healthy cereal to start your day`,
  },
  {
    id: 3,
    title: 'croissants',
    category: 'breakfast',
    price: 4,
    img: './images/croissants',
    desc: `Freshly baked croissants`,
  },
  {
    id: 4,
    title: 'cheeseburger',
    category: 'main',
    price: 8,
    img: './images/cheeseburger',
    desc: `Angus beef cheeseburger`,
  },
  {
    id: 5,
    title: 'panini',
    category: 'main',
    price: 7,
    img: './images/panini',
    desc: `Tasty cheese and tomato panini`,
  },
  {
    id: 6,
    title: 'salad',
    category: 'main',
    price: 7,
    img: './images/salad',
    desc: `A healthy and hearty salad`,
  },
  {
    id: 7,
    title: 'waffles',
    category: 'dessert',
    price: 5,
    img: './images/waffles',
    desc: `Delicious Belgian waffles`,
  },
  {
    id: 8,
    title: 'mille feuille',
    category: 'dessert',
    price: 6,
    img: './images/millefeuille',
    desc: `Succulent mille feuille`,
  },
  {
    id: 9,
    title: 'ice cream',
    category: 'dessert',
    price: 4,
    img: './images/icecream',
    desc: `Classic ice cream`,
  },
  {
    id: 10,
    title: 'ice cream',
    category: 'dessert',
    price: 4,
    img: './images/icecream',
    desc: `Classic ice cream in various flavours`,
  },
  {
    id: 11,
    title: 'milkshake',
    category: 'dessert',
    price: 4,
    img: './images/milkshake',
    desc: `Delicious milkshake in various flavours`,
  },
  {
    id: 12,
    title: 'orange juice',
    category: 'drinks',
    price: 2,
    img: './images/orangejuice',
    desc: `Freshly squeezed orange juice`,
  },
  {
    id: 13,
    title: 'soda',
    category: 'drinks',
    price: 1.5,
    img: './images/coke',
    desc: `A selection of popular sodas`,
  },
  {
    id: 14,
    title: 'tea',
    category: 'drinks',
    price: 2,
    img: './images/tea',
    desc: `English breakfast tea`,
  },
  {
    id: 15,
    title: 'coffee',
    category: 'drinks',
    price: 2,
    img: './images/coffee',
    desc: `Fresh coffee`,
  },

]